### ISSUE TITLE
civicpy cache truncated?

### ISSUE THREAD

**Issue by zhanyinx** [griffithlab/civicpy#148]
Hi there,

thanks for providing the tools for interacting with CIViC database.
Since a couple of days I encounter the problem with the cache. It appears that https://civicdb.org/downloads/nightly/nightly-civicpy_cache.pkl seems truncated.

When I run 

```
civicpy update
```

I got the following error message

```
WARNING:root:Downloading remote cache from https://civicdb.org/downloads/nightly/nightly-civicpy_cache.pkl.
Traceback (most recent call last):
  File "/usr/local/bin/civicpy", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/civicpy/cli.py", line 27, in update
    civic.update_cache(from_remote_cache=soft, local_cache_path=cache_save_path)
  File "/usr/local/lib/python3.7/site-packages/civicpy/civic.py", line 266, in update_cache
    load_cache(local_cache_path=local_cache_path)
  File "/usr/local/lib/python3.7/site-packages/civicpy/civic.py", line 196, in load_cache
    loaded_cache = pickle.load(pf)
_pickle.UnpicklingError: pickle data was truncated
```
Thanks for your help
Best
Zhan

**Comment by susannasiebert** [comment]
We recently made some changes to the CIViC database schema to accommodate fusions, which we suspect is causing issues when creating the pkl file. We will investigate further and hope to release a fix next week.

**Comment by anastasiabratulin** [comment]
@susannasiebert Hi, are there any updates?

**Comment by susannasiebert** [comment]
Still working on it. I hope to have it fixed by the end of the week.

**Comment by zhanyinx** [comment]
@susannasiebert Could you also make it possible to avoid updating the cache when running civicpy annotate-vcf?

**Comment by susannasiebert** [comment]
This isn't really documented, although it should be, but you can set the environment variable CACHE_TIMEOUT_DAYS to a higher value to prevent updating the cache. The default is 7 (days).

**Comment by susannasiebert** [comment]
A new version of civicpy is out now that fixes this issue. The remote pkl stored on CIViC has been updated and the VCF data releases have also been regenerated.

**Comment by zhanyinx** [comment]
the correct env variable for db cache timeout is: CIVICPY_CACHE_TIMEOUT_DAYS

**Comment by susannasiebert** [comment]
My apologies. Yes, it's `CIVICPY_CACHE_TIMEOUT_DAYS`.
